# frozen_string_literal: true

source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib' # JSON support
gem 'sqlite3'

group :test do
  gem 'minitest'
  gem 'rack-test'
end

group :development, :test do
  gem 'rake'
end
